#

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -31,17 +31,17 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
-    - name: report
-      run: mvn surefire-report:report  
-      
-    - name: Annotate failures
-      if: success() || failure()
-      uses: mikepenz/action-junit-report@v4.1.0
-      with:
-        name: Maven Tests
-        path: target/surefire-reports/*.xml
-        reporter: java-junit
-        fail-on-error: true   
+    # - name: report
+    #   run: mvn surefire-report:report  
+
+    # - name: Annotate failures
+    #   if: success() || failure()
+    #   uses: mikepenz/action-junit-report@v4.1.0
+    #   with:
+    #     name: Maven Tests
+    #     path: target/surefire-reports/*.xml
+    #     reporter: java-junit
+    #     fail-on-error: true   
 
     # - name: Publish Test Report
     #   uses: mikepenz/action-junit-report@v4
