#

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -31,14 +31,20 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
-    - name: Test
-      run: mvn test
-
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v4
-      if: success() || failure() # always run even if the previous step fails
+    - name: Annotate failures
+      if: success() || failure()
+      uses: mikepenz/action-junit-report@v4.1.0
       with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+        report_paths: junit.xml
+        include_passed: true
+        require_tests: true
+        require_passed_tests: true    
+          
+    # - name: Publish Test Report
+    #   uses: mikepenz/action-junit-report@v4
+    #   if: success() || failure() # always run even if the previous step fails
+    #   with:
+    #     report_paths: '**/build/test-results/test/TEST-*.xml'
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     # - name: Update dependency graph
